name: all_lint_rules_community
description: Automatically updated all lint rules file !
version: 0.0.41
repository: https://github.com/gaetschwartz/all_lint_rules

environment:
  sdk: ">=2.14.0 <4.0.0"
