name: extract_rules
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  args: ^2.3.0
  crypto: ^3.0.1
  freezed_annotation: ^2.1.0
  html: ^0.15.4
  http: ^0.13.3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  path: ^1.8.2
  pub_semver: ^2.1.0
  pubspec_parse: ^1.1.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  lints: ^2.0.0
