name: extract_rules
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies: 
  args: ^2.3.0
  crypto: ^3.0.1
  http: ^0.13.3
  intl: ^0.17.0
  pub_semver: ^2.1.0
  pubspec_parse: ^1.1.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
